name: Slack Demo
on:
  push:
jobs:
  GitHub-Actions-job-1:
    runs-on: ubuntu-latest
    env:
      SLACK_MESSAGE: 'From github action'
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
      # - name: Slack notify
      #   run: bash .github/scripts/slack_notify.sh
      - uses: actions/checkout@v3
      - run: |
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push